baseURL = 'https://ge-allemand.me'
languageCode = 'en-us'
title = 'Geraldine Allemand resume'
theme = 'devresume'
googleAnalytics = 'G-K57TX81Z36'

[params]
    baseURL = "https://ge-allemand.me"
    author = "geraldine allemand"
    description = "geraldine allemand resume. Strategic communicator / Project and event hands'on manager | communication director with 13+ years of experience handling complex projects and teams."

    primaryColor = "#61788c"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Geraldine Allemand"
        tagline = "Strategic communicator | Project and event hands'on manager"
        avatar = "Photo-ID-pro.jpeg"

    [params.contact]
        enable = true
        location = "Montpellier (FR)"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+33 6 85 33 41 54"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "geraldine.allemand[@]gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://remochat.github.io/resume/"
        text = "ge-allemand.me"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Communication & design"
        [[params.skills.list.items]]
        details = "Digital transformation"
        [[params.skills.list.items]]
        details = "People management"
        [[params.skills.list.items]]
        details = "Summit & event management"
        [[params.skills.list.items]]
        details = "Agile methodologies (scrum/kanban)"
        [[params.skills.list.items]]
        details = "Estimation and planning"

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Adobe Creative Suite"
        [[params.skills.list.items]]
        details = "SEO / SEA , Google Ads"
        [[params.skills.list.items]]
        details = "Html, CSS, JS"
        [[params.skills.list.items]]
        details = "CMS (Drupal, Wordpress, EZ)"
        [[params.skills.list.items]]
        details = "Git, GitHub"
        [[params.skills.list.items]]
        details = "Jira"
        [[params.skills.list.items]]
        details = "Figma, Miro, Mural"
        [[params.skills.list.items]]
        details = "MacOS, Windows & Linux"

        [[params.skills.list]]
        title = "Soft"
        [[params.skills.list.items]]
        details = "Impact driven"
        [[params.skills.list.items]]
        details = "Insightful"
        [[params.skills.list.items]]
        details = "Proactive"
        [[params.skills.list.items]]
        details = "Self reliant"
        [[params.skills.list.items]]
        details = "Team spirited"
    

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Master - Communication & cultural events"
        university = "Université d'Avignon (FR)"
        dates = "2009 - 2010"
        [[params.education.list]]
        degree = "Master - Businesses Communication"
        university = "Université de Montpellier (FR)"
        dates = "2008 - 2009"
        [[params.education.list]]
        degree = "Bachelor - Communication Sciences"
        university = "Université d'Avignon (FR)"
        dates = "2005 - 2008"

    [params.awards]
        enable = false

        # [[params.awards.list]]
        # name = ""
        # body = ""
        # date = ""
        # [[params.awards.list]]
        # name = ""
        # body = ""
        # date = ""

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "French"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Advanced - C1"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Motorbike racing"
        [[params.interests.list]]
        name = "Kitesurfing"
        [[params.interests.list]]
        name = "Digital culture"
        [[params.interests.list]]
        name = "Yoga / Handpan"

    [params.summary]
        enable = true
        text = """**13 years of experience in international advanced communication and digital transformation.**
- Driving strategy and communication with an agile mindset
- Crafting communication in brand strategies
- Organisation and handling in the management of international summits (international cooperation, sustainable development)
- Bridging mutli-functional roles to secure projects impact.engineers"""
        moto = "Moto: Simplicity is essential. Keep it is an art."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Digital project coordinator"
        dates = "2022 - Present"
        company = "CGI"
        skills = "Agile, Business process, Automation, Digital transformation, Corporate social responsability"
        location = "Montpellier (FR)"
        details = "Within the CGI Digital Innovation Center, supporting the digital transformation of companies by modeling, optimizing and automating internal processes."
        [[params.experience.list.items]]
        details = "Optimizing CGI worldwide onboarding process using automation (90.000 employees)"
        [[params.experience.list.items]]
        details = "Setting up and applying a change management strategy"
        [[params.experience.list.items]]
        details = "Structuring the pre-sales automation offer"
        [[params.experience.list.items]]
        details = "Organizing consultants unit to share knowledge and experiences, increasing approach consistency and deliveries"
        [[params.experience.list.items]]
        details = "Developing a corporate social responsibility (CSR) offer to train teams to the sustainable IT"

        [[params.experience.list]]
        title = "Independent Contractor - Communication & Design"
        dates = "2021 - 2022"
        company = "Beyondframes"
        skills = "Communication, Strategy, Design"
        location = "Zurich (CH)"
        [[params.experience.list.items]]
        details = "Helping S&M businesses build and monitor their strategy"
        [[params.experience.list.items]]
        details = "Communication consulting to strengthen the information exchange process between projects stakeholders"
        [[params.experience.list.items]]
        details = "Designing and maintaining brand consistency (print, digital) : brochure, social media graphics, event materials, websites, etc."

        [[params.experience.list]]
        title = "Co-director in charge of communication and eventsCo-director in charge of communication and events"
        dates = "2017-2019"
        company = "CARI NGO"
        skills = "Communication, high-level events management, Direction, Advocacy, International cooperation"
        location = "Montpellier (FR)"
        details = "Co director of CARI NGO - International cooperation / Land degradation. In charge of:**"
        [[params.experience.list.items]]
        details = "- Development of strategic directions & projects design in 10 countries in Africa & Middle East."
        [[params.experience.list.items]]
        details ="- Promotion of civil society input in the political arena managing the full life-cycle of events (United Nations & international summits)"
        
        details = "MANAGEMENT"
        [[params.experience.list.items]]
        details = "Advocating strategic directions to the executive council"
        [[params.experience.list.items]]
        details = "Internal operational management: growth, 1:1, development potentials, team building, feedback, etc."
        [[params.experience.list.items]]
        details = "External operational management: planning, KPI check, support and crisis management of highly distributed teams (potential unstructured state)"

        details = "COMMUNICATION & MEDIA RELATION"
        [[params.experience.list.items]]
        details = "360º communication campaigns"
        [[params.experience.list.items]]
        details = "Digital transformation"
        [[params.experience.list.items]]
        details = "Crisis communication"
        [[params.experience.list.items]]
        details = "Web marketing strategy & Community management"
        [[params.experience.list.items]]
        details = "Implementation of a media relations policy (communication on publications, reports, international events and activities...)"
        [[params.experience.list.items]]
        details = "Press impact analysis, press kit writing and press conference organization"
        [[params.experience.list.items]]
        details = "Developing high-quality event communication (eg. Save the dates, invitations, booklets, slide decks)"

        details = "EVENTS & ADVOCACY"
        details = "CARI events are critical platforms to share recommendations from civil society and facilitate dialogue among stakeholders: scientists, policymakers, academics, multilateral organisations, NGOs and others."
        [[params.experience.list.items]]
        details = "Group facilitation in a multicultural environment"
        [[params.experience.list.items]]
        details = "Links with international and regional organisations"
        [[params.experience.list.items]]
        details = "Managing the full life-cycle of high-level and international Summits"
        [[params.experience.list.items]]
        details = "Promotion of civil society input in the political arena"
        [[params.experience.list.items]]
        details = "Support international networks teams and program managers in the implementation of advocacy actions: defining an influencing strategy, meeting decision-makers, responding to government consultations..."

        [[params.experience.list]]
        title = "Chief Technology Officer"
        dates = "2017 - 2019"
        company = "TellMePlus"
        skills = "Golang, Streaming, k8s"
        location = "Montpellier (FR)"
        details = "Drive the roadmap, technical strategy and key architecture of Predictive Objects to transform our proof of concept into product. A clound agnostic platform, available on premise, able to ingest realtime sensors data, compute extended features, build datasets and use supervised machine learning to train Predictive Objects models to anticipate failures on industrial plants."

        [[params.experience.list]]
        title = "Engineering Manager - DevOps"
        dates = "2015 - 2017"
        company = "TellMePlus"
        skills = "Golang, Python, Terraform"
        location = "Montpellier (FR)"
        details = "Manage transversal team supporting Predictive Objects in multi cloud environments. Promoted development good practices such as testing, continuous deployment, communication, security guidelines and tooling to the engineering teams."

        [[params.experience.list]]
        title = "CTO / Co-Founder"
        dates = "2014 - 2015"
        company = "Arksens cyber security"
        skills = "Ruby on rails, Proxmox, Debian, Ansible"
        location = "Mauritius"
        details = "Arksens Cyber Security is a digital security vendor for small & medium sized companies. It provides & customizes a set of open source tools and services to help companies autonomously reducing cyber threats by themselves at a controlled cost."

        [[params.experience.list]]
        title = "Software Engineer - Backend"
        dates = "2013 - 2014"
        company = "TellMePlus"
        skills = "Java, MongoDB"
        location = "Montpellier (FR)"
        details = "Shopping Intelligence, Recommandation over Big-Data using NoSQL & CHOCO library to produce fined grained recommandation."

        [[params.experience.list]]
        title = "Research Engineer"
        dates = "2013"
        company = "LIRMM - Montpellier Laboratory of Computer Science, Robotics, and Microelectronics"
        skills = "Java, Choco"
        location = "Montpellier (FR)"
        details = "Constraint Programming. Demonstrate constraint programming capabilities on concrete business cases."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2011 - 2013"
        company = "Sanofi"
        skills = "Objective-C, SQLite"
        location = "Montpellier (FR)"
        details = "Created a sqlite based framework for mobile applications designed to compound with security guidelines of clinical studies." 

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Artistic Pictures"
        meta = "Photography, Software Development"
        tagline = "Capturing the perfect moment, artistic vision in mind"

        [[params.projects.list]]
        title = "Construction Coordinator / builder"
        meta = "Construction"
        tagline = "Design, creation, and construction of my personal house"

        [[params.projects.list]]
        title = "Le Sonambule, volunteering"
        meta = "Arts - Music"
        tagline = "Contributing to make the organisation to offer concerts at a fair price"

    [params.information]
        enable = false

        # [[params.information.list]]
        # title = ""
        # [[params.information.list.items]]
        # details = ""
        # [[params.information.list.items]]
        # details = ""

        [[params.information.list]]
        title = "Interests"
        details = "Motorbike racing, Kitesurfing, Photography, Travelling"

    [params.recommendations]
        enable = true

        # [[params.information.list]]
        # title = ""
        # [[params.information.list.items]]
        # details = ""
        # [[params.information.list.items]]
        # details = ""

        [[params.recommendations.list]]
        title = "Mike Pilawski"
        meta = "Mike was David's mentor"
        details = """David is a great technology leader and an engineering manager. He is a strong architect capable of thinking through complex architectural choices and arriving at simple and reliable solutions. He can take large, complex projects, identify key risks and direct the team through milestones to completion. He is also a great manager who deeply cares for his team and invests time to help his team members grow.
        
It was a real privilege working with David and I hope I will have the opportunity to do it again."""

        [[params.recommendations.list]]
        title = "Jakub Skoczeń"
        meta = "Jakub reported directly to David"
        details = "David is an exceptional hands-on manager with extensive technical knowledge and a pragmatic approach to problem-solving. He has a talent for building efficient and successful teams full of trust, and his collaborative leadership style inspires great results. I highly recommend him as a skilled and knowledgeable leader."

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fa fa-download"
        url = "/david_terranova_en.pdf"
        title = "download as pdf"
        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/davidterranova"
        title = "davidterranova"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/terranovadavid"
        title = "terranovadavid"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/terranovadavid"
        title = "@terranovadavid"
