baseURL = 'https://ge-allemand.me'
languageCode = 'en-us'
title = 'Geraldine Allemand resume'
theme = 'devresume'
googleAnalytics = 'G-90QQ9M98J3'

[params]
    baseURL = "https://ge-allemand.me"
    author = "geraldine allemand"
    description = "geraldine allemand resume. Communication expert / Digital transformation & Sustainability / Project and event hands'on manager | Communication director with 14+ years of experience handling complex projects, environment, and teams."

    primaryColor = "#61788c"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Geraldine Allemand"
        tagline = "Strategic communicator | Change Management, Innovation & Sustainability"
        # High-level Event Manager, Innovation & Sustainibility
        # Digital Innovation, Change Management & Sustainability
        # Digital transformation & Sustainability
        avatar = "Photo-ID-pro.jpeg"

    [params.contact]
        enable = true
        location = "Montpellier (FR)"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+33 6 85 33 41 54"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "geraldine.allemand[@]gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://remochat.github.io/resume/"
        text = "ge-allemand.me"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Communication & Design"
        [[params.skills.list.items]]
        details = "Sustainibility"
        [[params.skills.list.items]]
        details = "Digital transformation"
        [[params.skills.list.items]]
        details = "People management"
        [[params.skills.list.items]]
        details = "International events management"
        [[params.skills.list.items]]
        details = "Agile methodologies (scrum/kanban)"

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Adobe Creative Suite"
        [[params.skills.list.items]]
        details = "SEO / SEA, Google Ads"
        [[params.skills.list.items]]
        details = "Html, CSS, JS"
        # [[params.skills.list.items]]
        # details = "CMS (Drupal, Wordpress)"
        [[params.skills.list.items]]
        details = "Git, GitHub, Jira"
        [[params.skills.list.items]]
        details = "Figma, Miro, Draw.io"
        [[params.skills.list.items]]
        details = "MacOS, Windows & Linux"

        [[params.skills.list]]
        title = "Soft"
        # details = "Behavioural Competencies"
        [[params.skills.list.items]]
        details = "Fostering Cooperation"
        [[params.skills.list.items]]
        details = "High sense of interculturality"
        [[params.skills.list.items]]
        details = "Impact driven"
        # details = "Result Orientation"
        [[params.skills.list.items]]
        details = "Insightful"
        [[params.skills.list.items]]
        details = "Proactive"
        [[params.skills.list.items]]
        details = "Continuous Improvement"
        # details = "Self reliant"
        [[params.skills.list.items]]
        details = "Team spirited"
    

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Master - Communication & cultural events"
        university = "Université d'Avignon (FR)"
        dates = "2009 - 2010"
        [[params.education.list]]
        degree = "Master - Businesses Communication"
        university = "Université de Montpellier (FR)"
        dates = "2008 - 2009"
        [[params.education.list]]
        degree = "Bachelor - Communication Sciences"
        university = "Université d'Avignon (FR)"
        dates = "2005 - 2008"
        
    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "French"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Advanced - C1"
        [[params.languages.list]]
        name = "Spanish"
        level = "Independent user level"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Motorbike"
        [[params.interests.list]]
        name = "Kitesurfing"
        [[params.interests.list]]
        name = "Digital culture"
        [[params.interests.list]]
        name = "Yoga / Handpan"

    [params.awards]
        enable = true

        # [[params.awards.list]]
        # name = "Swiss Design Contest - Winner"
        # body = "Creation of an entire brand design & communication strategy."
        # date = "2021"
        # [[params.awards.list]]
        # name = "Prize-winning team following a call for proposals Marseille - Provence 2013 : European Capitals of Culture"
        # body = "In collaboration with the MuCEM Museum : Proposal of mechanisms for promoting collections and integrating the structure from the local to the Euro-Mediterranean vision, Creation of a new scenography and spatial design, and mediation process."
        # date = "2009"

    [params.summary]
        enable = true
        text = """**14 years of experience in international advanced communication and digital transformation across Europe, North America, West Africa, and the Middle East.**
- Driving strategy and communication with an agile mindset in complex projects, environment, and teams
- Managing international high-level events focused on international cooperation
- Bridging multi-functional roles to ensure projects impact
- Turning sustainability ambition into action through business strategies consulting"""
        moto = "Moto: Simplicity is essential. Keep it is an art."
        # handling in the management of international summits (international cooperation, sustainable development)
        # Intersecting business model and technology transformation to unlock Cie agility

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Process & Digital Transformation Consultant"
        dates = "Feb. 2024 - Present Day"
        company = "CGI - France"
        skills = "Digital transformation, Change Management, Sustainability"
        location = "Montpellier (FR)"
        details = "My role is both strategic and hands-on, requiring a mix of leadership, technical expertise, and business acumen."
        [[params.experience.list.items]]
        details = "Driving digital transformation across industries, and the importance of integrating Al as a key technology to advance climate tech and climate action."
        [[params.experience.list.items]]
        details = "Communicating with stakeholders to understand their requirements, provide updates on project progress, and manage expectations"
        [[params.experience.list.items]]
        details = "Supporting clients in their Change management and Smart automation projects"
        [[params.experience.list.items]]
        details = "Contributing to the development of the BU: Digitalization for Sustainability"


        [[params.experience.list]]
        title = "UNFCCC COP28 - Civil Society Liaison Officer"
        dates = "Oct. - Dec. 2023"
        company = "Expo City Dubai - United Arab Emirates"
        skills = "High-level event management, Communication, International Development"
        location = "Dubaï (UAE)"
        details = "Initializing for the very first time in the UAE history, a dynamic-event space to let civil society expresses its will and recommendations: the Voice for Action hub."
        [[params.experience.list.items]]
        details = "Designing and planning the Voice for Action hub, ensuring its seamless integration into all aspects of operational planning"
        [[params.experience.list.items]]
        details = "Leading the effective communication between the Civil society and the Host country, engaging with a wide array of stakeholders"
        [[params.experience.list.items]]
        details = "Handling sensitive topics such as security issues"
        [[params.experience.list.items]]
        details = "Developing and executing a comprehensive strategy to ensure activists, volunteers and climate focussed partner organizations are accounted for in the Voice for Action planning"
        [[params.experience.list.items]]
        details = "Cultivating and strengthening relationships with key stakeholders, including Civil society organizations, indigenous groups, youth activists, and other influential voices."
        [[params.experience.list.items]]
        details = "Contributing to post-event reports and recommendations for enhancing future engagements"
       

        [[params.experience.list]]
        title = "Digital project coordinator"
        dates = "2022 - Sept. 2023"
        company = "CGI - France"
        skills = "Digital transformation, Business process Consulting, Automation"
        location = "Montpellier (FR)"
        details = "Within the CGI Digital Innovation Center, supporting the digital transformation of companies by modeling, optimizing and automating internal processes."
        [[params.experience.list.items]]
        details = "Optimizing CGI worldwide onboarding process using automation (90.000 employees)"
        [[params.experience.list.items]]
        details = "Animating workshops to express final users needs, elaborating prioritized stories, and optimizing features through continuous iterations"
        [[params.experience.list.items]]
        details = "Structuring the pre-sales automation offer"
        [[params.experience.list.items]]
        details = "Organizing consultant unit to share knowledge and experiences, increasing approach consistency and deliveries"
        [[params.experience.list.items]]
        details = "Developing a corporate social responsibility (CSR) offer to train teams to the sustainable IT"

        [[params.experience.list]]
        title = "Contractor - Communication & Design"
        dates = "2021 - 2022"
        company = "Beyondframes. - Switzerland"
        skills = "Communication Strategy, Print & digital design"
        location = "Zurich (CH)"
        details = "Beyond frames offers complete personalized services to entrepreneurs, with deep expertise in communication, brand strategy, design and digital."
        [[params.experience.list.items]]
        details = "Helping S&M businesses build and monitor their strategy"
        [[params.experience.list.items]]
        details = "Communication consulting to strengthen the information exchange process between projects stakeholders"
        [[params.experience.list.items]]
        details = "Crafting user experience from the idea to the front-end development: UI/UX, accessibility, sustainable IT"
        [[params.experience.list.items]]
        details = "Designing and maintaining brand consistency: brochure, social media graphics, event materials, websites, etc."

        [[params.experience.list]]
        title = "Co-director in charge of communication and events"
        dates = "2017-2019"
        company = "CARI NGO - International cooperation"
        skills = "International Development, Management, Communication, High-level event management, Advocacy"
        location = "Montpellier (FR)"
        details = "French NGO coordinating 3 international civil society networks in 10 countries (Africa & Middle East) and organizing international environmental summits. As Co-director, I was in charge of:"
        [[params.experience.list.items]]
        details = "Development of strategic directions & projects design"
        [[params.experience.list.items]]
        details ="Promotion of civil society input in the political arena managing the full life-cycle of events (United Nations & international summits)"
        [[params.experience.list.items]]
        details = "Internal operational management: growth, 1:1, team building, feedback, etc."
        [[params.experience.list.items]]
        details = "360º communication campaigns and crisis communication."
        

        [[params.experience.list]]
        title = "Communication officer"
        dates = "2013 - 2016"
        company = "CARI NGO - International cooperation"
        skills = "International Development, Communication, Media Relation, Project management"
        location = "Montpellier (FR)"
        details = "As Communication strategic focal point for 3 civil society networks in Sahelian and Maghreb region, I created communication tools to assist dialogue between actors involved in drylands."
        [[params.experience.list.items]]
        details = "Managing international media relation strategy and execution"
        [[params.experience.list.items]]
        details = "Create and implement organizational digital communication plans that align with the NGO’s missions and brand"
        [[params.experience.list.items]]
        details = "Creation of the communication unit & new processes : objectives, monitoring, communication security policy, etc."
        [[params.experience.list.items]]
        details = "Editorial lead: 9 websites, 5 newsletters, +10 000 followers, dozen of print supports (eg. user guides, magazines...)."
         

        [[params.experience.list]]
        title = "Communication & Side event manager"
        dates = "2013"
        company = "Art souterrain - Canada"
        skills = "Communication, media relation, event management, artist support"
        location = "Montreal (CA)"
        details = "Communication and implementation of cultural projects promoting contemporary art in an urban environment, 100.000 visitors per day."

        [[params.experience.list]]
        title = "Communication & project manager"
        dates = "2010-2012"
        company = "Baccarat - France"
        skills = "Communication, Event management, Territorial development"
        location = "Baccarat (FR)"
        details = "Key player in the creation of a territorial project of 2 million euros based on two brownfields of Baccarat SA including : a 200m2 international exhibition gallery, an artists’ incubator, a training center, and an R&D center."

        [[params.experience.list]]
        title = "Projet manager"
        dates = "2009"
        company = "Université de Montpellier - France"
        skills = "Communication, Design, Architecture"
        location = "Montpellier (FR)"
        details = "Carrying out an accessibility and signage diagnosis to improve the integration of the diversity of users in complex environment." 

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Les Chèvres de la Garrigue"
        meta = "Agroecology & Biodiversity" 
        # Support to a collective participative approach in Goats production
        tagline = "Support for Goat cheese production and the protection of the Rove breed, a distinctive local breed emblematic of the Garrigues in the South of France | 2022-2024"

        [[params.projects.list]]
        title = "Construction Coordinator, Montpellier"
        meta = "Construction"
        tagline = "Design, and construction of a entire house | 2019-2020"
        
        [[params.projects.list]]
        title = "Action Sport, Montpellier"
        meta = "Kitesurf - Wakeboard"
        tagline = "FISE World Montpellier / Action sport festival | 2019"

        [[params.projects.list]]
        title = "Le Sonambule, Gignac"
        meta = "Arts - Music"
        tagline = "Contributing to make the organisation to offer concerts at a fair price | 2016"

        [[params.projects.list]]
        title = "Le Vieux Canal, Azerailles"
        meta = "Arts - Music"
        tagline = "Developing a new festival (communicaiton, partnership, and organization) to disseminate current music in all its diversity | 2011-2012"

    [params.information]
        enable = true

        [[params.information.list]]
        title = "2021 | Zürich Design Contest - Winner"
        [[params.information.list.items]]
        details = "Creation of an entire brand design & communication strategy."

        [[params.information.list]]
        title = "2009 | Prize-winning team following a Call for proposals Marseille - Provence 2013: European Capitals of Culture"
        [[params.information.list.items]]
        details = "In collaboration with the Museum of European and Mediterranean Civilisations (MuCEM): Proposal of mediaiton mechanisms & processes for promoting collections and integrating the structure from the local to the Euro-Mediterranean vision, and Creation of a new scenography and spatial design for temporary exhibition."

    [params.recommendations]
        enable = true

        # [[params.information.list]]
        # title = ""
        # [[params.information.list.items]]
        # details = ""
        # [[params.information.list.items]]
        # details = ""

        [[params.recommendations.list]]
        title = "Marcos Montoiro"
        meta = "External Relations Officer at United Nations Convention to Combat Desertification"
        details = '"(...) Ms. Allemand has shown during all these years an impressive sensibility to portray on her publications, pictures and digital work the testimonies of those working on the ground trying to make a better living from a degraded land. She is a hard worker and very rigorous professional that has shown a strong commitment for the protection of the environment and the achievement of the Sustainable Development Goals. Working with Ms. Geraldine Allemand during all these years has been a great pleasure, she is a great team player and brings original solutions to challenges we faced."'
        
        [[params.recommendations.list]]
        title = "Bianca Auclair"
        meta = "Director Business Consulting / CGI Montreal"
        details = '"Working with Géraldine was both a great joy and the discovery of a brilliant woman. Her professionalism and ability to create connections are undeniable. The human approach and expertise she brought to the project were of high quality. I hope to work with you again."'

        
    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fa fa-download"
        url = "/geraldine_allemand_en.pdf"
        title = "download as pdf"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/geraldineallemand/"
        title = "geraldineallemand"
        [[params.social.list]]
        icon = "fa fa-globe"
        url = "https://beyondframes.co"
        title = "website"
        # [[params.social.list]]
        # icon = "fab fa-dribbble"
        # url = "https://dribbble.com/beyondframes/"
        # title = "beyondframes"
