baseURL = 'https://ge-allemand.me'
languageCode = 'en-us'
title = 'Geraldine Allemand resume'
theme = 'devresume'
googleAnalytics = 'G-90QQ9M98J3'

[params]
    baseURL = "https://ge-allemand.me"
    author = "geraldine allemand"
    description = "geraldine allemand resume. Strategic communicator / Project and event hands'on manager | communication director with 13+ years of experience handling complex projects and teams."

    primaryColor = "#61788c"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Geraldine Allemand"
        tagline = "Strategic communicator | Project and event hands'on manager"
        avatar = "Photo-ID-pro.jpeg"

    [params.contact]
        enable = true
        location = "Montpellier (FR)"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+33 6 85 33 41 54"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "geraldine.allemand[@]gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://remochat.github.io/resume/"
        text = "ge-allemand.me"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Communication & design"
        [[params.skills.list.items]]
        details = "Digital transformation"
        [[params.skills.list.items]]
        details = "People management"
        [[params.skills.list.items]]
        details = "Summit & event management"
        [[params.skills.list.items]]
        details = "Agile methodologies (scrum/kanban)"
        [[params.skills.list.items]]
        details = "Estimation and planning"

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Adobe Creative Suite"
        [[params.skills.list.items]]
        details = "SEO / SEA , Google Ads"
        [[params.skills.list.items]]
        details = "Html, CSS, JS"
        [[params.skills.list.items]]
        details = "CMS (Drupal, Wordpress, EZ)"
        [[params.skills.list.items]]
        details = "Git, GitHub"
        [[params.skills.list.items]]
        details = "Jira"
        [[params.skills.list.items]]
        details = "Figma, Miro, Mural"
        [[params.skills.list.items]]
        details = "MacOS, Windows & Linux"

        [[params.skills.list]]
        title = "Soft"
        [[params.skills.list.items]]
        details = "Impact driven"
        [[params.skills.list.items]]
        details = "Insightful"
        [[params.skills.list.items]]
        details = "Proactive"
        [[params.skills.list.items]]
        details = "Self reliant"
        [[params.skills.list.items]]
        details = "Team spirited"
    

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Master - Communication & cultural events"
        university = "Université d'Avignon (FR)"
        dates = "2009 - 2010"
        [[params.education.list]]
        degree = "Master - Businesses Communication"
        university = "Université de Montpellier (FR)"
        dates = "2008 - 2009"
        [[params.education.list]]
        degree = "Bachelor - Communication Sciences"
        university = "Université d'Avignon (FR)"
        dates = "2005 - 2008"

    [params.awards]
        enable = false

        # [[params.awards.list]]
        # name = ""
        # body = ""
        # date = ""
        # [[params.awards.list]]
        # name = ""
        # body = ""
        # date = ""

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "French"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Advanced - C1"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Motorbike"
        [[params.interests.list]]
        name = "Kitesurfing"
        [[params.interests.list]]
        name = "Digital culture"
        [[params.interests.list]]
        name = "Yoga / Handpan"

    [params.summary]
        enable = true
        text = """**13 years of experience in international advanced communication and digital transformation.**
- Driving strategy and communication with an agile mindset
- Crafting communication in brand strategies
- Organisation and handling in the management of international summits (international cooperation, sustainable development)
- Bridging mutli-functional roles to secure projects impact"""
        moto = "Moto: Simplicity is essential. Keep it is an art."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Digital project coordinator"
        dates = "2022 - Present"
        company = "CGI - France"
        skills = "Digital transformation, Business process, Automation"
        location = "Montpellier (FR)"
        details = "Within the CGI Digital Innovation Center, supporting the digital transformation of companies by modeling, optimizing and automating internal processes."
        [[params.experience.list.items]]
        details = "Optimizing CGI worldwide onboarding process using automation (90.000 employees)"
        [[params.experience.list.items]]
        details = "Setting up and applying a change management strategy"
        [[params.experience.list.items]]
        details = "Structuring the pre-sales automation offer"
        [[params.experience.list.items]]
        details = "Organizing consultants unit to share knowledge and experiences, increasing approach consistency and deliveries"
        [[params.experience.list.items]]
        details = "Developing a corporate social responsibility (CSR) offer to train teams to the sustainable IT"

        [[params.experience.list]]
        title = "Contractor - Communication & Design"
        dates = "2021 - 2022"
        company = "Beyondframes - Switzerland"
        skills = "Communication, Strategy, Print & digital design"
        location = "Zurich (CH)"
        details = "Beyond frames offers complete personalized services to entrepreneurs, with deep expertise in communication, brand strategy, design and digital."
        [[params.experience.list.items]]
        details = "Helping S&M businesses build and monitor their strategy"
        [[params.experience.list.items]]
        details = "Communication consulting to strengthen the information exchange process between projects stakeholders"
        [[params.experience.list.items]]
        details = "Designing and maintaining brand consistency : brochure, social media graphics, event materials, websites, etc."

        [[params.experience.list]]
        title = "Co-director in charge of communication and events"
        dates = "2017-2019"
        company = "CARI NGO - International cooperation"
        skills = "Management, Communication, High-level events management, Advocacy"
        location = "Montpellier (FR)"
        details = "French NGO coordinating 3 international civil society networks in 10 countries (Africa & Middle East) and organizing international environmental summits. As Co-director, I was in charge of:"
        [[params.experience.list.items]]
        details = "Development of strategic directions & projects design"
        [[params.experience.list.items]]
        details ="Promotion of civil society input in the political arena managing the full life-cycle of events (United Nations & international summits)"
        [[params.experience.list.items]]
        details = "Internal operational management: growth, 1:1, team building, feedback, etc."
        [[params.experience.list.items]]
        details = "360º communication campaigns and crisis communication"
        

        [[params.experience.list]]
        title = "Communication officer"
        dates = "2013 - 2016"
        company = "CARI NGO - International cooperation"
        skills = "Communication, media relation, project management"
        location = "Montpellier (FR)"
        details = "As Communication strategic focal point for 3 civil society networks in Sahelian and Maghreb region, I created communication tools to assist dialogue between actors involved in drylands."
        [[params.experience.list.items]]
        details = "Managing international media relation strategy and execution"
        [[params.experience.list.items]]
        details = "Create and implement organizational digital communication plans that align with the NGO’s missions and brand"
        [[params.experience.list.items]]
        details = "Creation of the communication unit & new processes : objectives, monitoring, communication security policy, etc."
        [[params.experience.list.items]]
        details = "Editorial lead: 9 websites, 5 newsletters, +10 000 followers, dozen of print supports (eg. user guides, magazines...)"
         

        [[params.experience.list]]
        title = "Communication & Side event manager"
        dates = "2013"
        company = "Art souterrain - Canada"
        skills = "Communication, media relation, event management, artist support"
        location = "Montreal (CA)"
        details = "Communication and implementation of cultural projects promoting contemporary art in an urban environment, 100.000 visitors per day"

        [[params.experience.list]]
        title = "Communication & project manager"
        dates = "2010-2012"
        company = "Baccarat - France"
        skills = "Communication, event management, territorial development"
        location = "Baccarat (FR)"
        details = "Key player in the creation of a territorial project of 2 million euros based on two brownfields of Baccarat SA including : a 200m2 international exhibition gallery, an artists’ incubator, a training center, and an R&D center"

        [[params.experience.list]]
        title = "Projet manager"
        dates = "2009"
        company = "Université de Montpellier - France"
        skills = "Communication, Design, architecture, analysis"
        location = "Montpellier (FR)"
        details = "Carrying out an accessibility and signage diagnosis to improve the integration of the diversity of users in complex environment." 

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Action Sport, volunteering"
        meta = "Kitesurf - Wakeboard"
        tagline = "FISE World Montpellier / Action sport festival"

        [[params.projects.list]]
        title = "Construction Coordinator / builder"
        meta = "Construction"
        tagline = "Design, creation, and construction of my personal house"

        [[params.projects.list]]
        title = "Le Sonambule, volunteering"
        meta = "Arts - Music"
        tagline = "Contributing to make the organisation to offer concerts at a fair price"

    [params.information]
        enable = false

        # [[params.information.list]]
        # title = ""
        # [[params.information.list.items]]
        # details = ""
        # [[params.information.list.items]]
        # details = ""

        [[params.information.list]]
        title = "Interests"
        details = "Motorbike, Digital culture, Kitesurfing, Yoga / Meditation / Hand pan"

    [params.recommendations]
        enable = true

        # [[params.information.list]]
        # title = ""
        # [[params.information.list.items]]
        # details = ""
        # [[params.information.list.items]]
        # details = ""

        [[params.recommendations.list]]
        title = "Marcos Montoiro"
        meta = "Marcos was the United State Liaison Officer for the Civil society"
        details = "(...) Ms. Allemand has shown during all these years an impressive sensibility to portray on her publications, pictures and digital work the testimonies of those working on the ground trying to make a better living from a degraded land. She is a hard worker and very rigorous professional that has shown a strong commitment for the protection of the environment and the achievement of the Sustainable Development Goals. Working with Ms. Geraldine Allemand during all these years has been a great pleasure, she is a great team player and brings original solutions to challenges we faced."

        
    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fa fa-download"
        url = "/geraldine_allemand_en.pdf"
        title = "download as pdf"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/geraldineallemand/"
        title = "geraldineallemand"
        [[params.social.list]]
        icon = "fa fa-globe"
        url = "https://beyondframes.co/#contact-section"
        title = "website"
        # [[params.social.list]]
        # icon = "fab fa-dribbble"
        # url = "https://dribbble.com/beyondframes/"
        # title = "beyondframes"
